title: "Hareesh Ashok Kumar"
author: "Hareesh"
description: "My first website!!!"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true       # show article excerpts on the home page
show_social: true          # hemlo
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false          # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md",title: "About" }
  - {file: "Projects.md",title: "Projects"}
  - {file: "/myresume.pdf",title: "CV" }

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:hareesh9910.acad@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/hareesH-A-K"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/_hareesh_a_k/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

